"""initial_schema"""

revision = 'e7d457108ddb'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('distance_desc', sa.String(length=50), nullable=False),
    sa.Column('hero_image_url', sa.String(length=255), nullable=False),
    sa.Column('care_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('is_demo_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_phone'), 'profiles', ['phone'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_chat_sessions_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_profile_id'), 'chat_sessions', ['profile_id'], unique=False)
    op.create_table('elders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('status_text', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_elders_institution_id_institutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elders'))
    )
    op.create_table('institution_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('relation_label', sa.String(length=40), nullable=False),
    sa.Column('stay_duration_label', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at_label', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_institution_reviews_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_reviews'))
    )
    op.create_table('institution_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('highlight_1', sa.String(length=40), nullable=True),
    sa.Column('highlight_2', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_institution_services_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_services'))
    )
    op.create_table('institution_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_institution_tags_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_tags'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('error_state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('dynamics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('elder_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], name=op.f('fk_dynamics_elder_id_elders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dynamics'))
    )
    op.create_index(op.f('ix_dynamics_elder_id'), 'dynamics', ['elder_id'], unique=False)
    op.create_index(op.f('ix_dynamics_happened_at'), 'dynamics', ['happened_at'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('elder_id', sa.String(length=36), nullable=False),
    sa.Column('range_bucket', sa.String(length=10), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], name=op.f('fk_health_metrics_elder_id_elders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_metrics'))
    )
    op.create_index(op.f('ix_health_metrics_elder_id'), 'health_metrics', ['elder_id'], unique=False)
    op.create_index(op.f('ix_health_metrics_range_bucket'), 'health_metrics', ['range_bucket'], unique=False)
    op.create_index(op.f('ix_health_metrics_recorded_at'), 'health_metrics', ['recorded_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('elder_id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('package_type', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=50), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('relationship_label', sa.String(length=20), nullable=False),
    sa.Column('signature_data_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], name=op.f('fk_orders_elder_id_elders')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_orders_institution_id_institutions')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_orders_profile_id_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_profile_id'), 'orders', ['profile_id'], unique=False)
    op.create_table('service_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('elder_id', sa.String(length=36), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('time_label', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], name=op.f('fk_service_logs_elder_id_elders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_logs'))
    )
    op.create_index(op.f('ix_service_logs_day_index'), 'service_logs', ['day_index'], unique=False)
    op.create_index(op.f('ix_service_logs_elder_id'), 'service_logs', ['elder_id'], unique=False)
    op.create_table('dynamic_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dynamic_id', sa.String(length=36), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('time_label', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamics.id'], name=op.f('fk_dynamic_comments_dynamic_id_dynamics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dynamic_comments'))
    )
    op.create_table('dynamic_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dynamic_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_id'], ['dynamics.id'], name=op.f('fk_dynamic_likes_dynamic_id_dynamics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_dynamic_likes_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dynamic_likes')),
    sa.UniqueConstraint('dynamic_id', 'profile_id', name='uq_dynamic_like_dynamic_profile')
    )
    op.create_table('order_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_reviews_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_reviews'))
    )
    op.create_index(op.f('ix_order_reviews_order_id'), 'order_reviews', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_reviews_order_id'), table_name='order_reviews')
    op.drop_table('order_reviews')
    op.drop_table('dynamic_likes')
    op.drop_table('dynamic_comments')
    op.drop_index(op.f('ix_service_logs_elder_id'), table_name='service_logs')
    op.drop_index(op.f('ix_service_logs_day_index'), table_name='service_logs')
    op.drop_table('service_logs')
    op.drop_index(op.f('ix_orders_profile_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_health_metrics_recorded_at'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_range_bucket'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_elder_id'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index(op.f('ix_dynamics_happened_at'), table_name='dynamics')
    op.drop_index(op.f('ix_dynamics_elder_id'), table_name='dynamics')
    op.drop_table('dynamics')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('institution_tags')
    op.drop_table('institution_services')
    op.drop_table('institution_reviews')
    op.drop_table('elders')
    op.drop_index(op.f('ix_chat_sessions_profile_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_profiles_phone'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('institutions')
    # ### end Alembic commands ###
